apiVersion: v1
kind: Service
metadata:
  name: k8s-cluster-ui
spec:
  selector:
    app: k8s-cluster-ui
  ports:
  - name: api
    port: 5000
    targetPort: 5000
  - name: frontend
    port: 8080
    targetPort: 8080
  type: ClusterIP
