version: '3'

services:
  k8s-dashboard:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "5000:5000"  # Backend API
      - "8080:8080"  # Frontend
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=5000
      - DEBUG=True
      - ENABLE_CORS=True
    volumes:
      - ~/.aws:/root/.aws:ro  # For AWS profiles (optional)
    restart: unless-stopped
